### ISSUE TITLE
[STORY] User Signup

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#13]
**Story**
As a user, I should be able to sign up so that I may create an account

**Feature [User Login](https://github.com/tysonkaufmann/su-go/issues/5 )**

**Related Developer Tasks**
- [Create Signup UI](https://github.com/tysonkaufmann/su-go/issues/14)
- [Create an User collection and UserInfo model](https://github.com/tysonkaufmann/su-go/issues/15)
- [Create a Signup endpoint](https://github.com/tysonkaufmann/su-go/issues/16)
- [Add scripts to front-end to handle the signup](https://github.com/tysonkaufmann/su-go/issues/17)
- [Add a functional tests for signup](https://github.com/tysonkaufmann/su-go/issues/18)

**Acceptance Test**
- Given I am not logged in and on the login page,
- When I click the signup button and enter in my user details then click submit,
- Then a new account should be created with my user details and I should be able to login
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
