### ISSUE TITLE
[STORY] Reset Password

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#19]
**Story**
As a user, I should be able to reset my password if I have forgotten it so that I may be able to login to my account

**Feature [User Login](https://github.com/tysonkaufmann/su-go/issues/5 )**

**Related Developer Tasks**
- [Create a Reset Password Request UI](https://github.com/tysonkaufmann/su-go/issues/20)
- [Create a Reset Password Request endpoint](https://github.com/tysonkaufmann/su-go/issues/21)
- [Send an Email with the Verification Code](https://github.com/tysonkaufmann/su-go/issues/22)
- [Create a Change Password UI](https://github.com/tysonkaufmann/su-go/issues/23)
- [Create a Change Password endpoint](https://github.com/tysonkaufmann/su-go/issues/24)
- [Add Scripts to the front-end to handle the reset password](https://github.com/tysonkaufmann/su-go/issues/25)
- [Add functional tests for reset password](https://github.com/tysonkaufmann/su-go/issues/26)

**Acceptance Test 1**
- Given I am logged in and on the user profile page,
- When I click edit profile and the click reset password,
- Then I should be sent a verification code to my registered email that I can enter to reset my password
- [x] Passes

**Acceptance Test 2**
- Given I am not logged in and on the login page,
- When I click the "Forgot my password" button,
- Then I should be sent a verification code to my registered email that I can enter to reset my password
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
