### ISSUE TITLE
[STORY] Logout

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#27]
**Story**
As a user, I should be able to logout of the application so that I may restrict others from using my account

**Feature [User Login](https://github.com/tysonkaufmann/su-go/issues/5 )**

**Related Developer Tasks**
- [Logout Changes to the Front-end](https://github.com/tysonkaufmann/su-go/issues/28)
- [Add a functional test for logout](https://github.com/tysonkaufmann/su-go/issues/30)

**Acceptance Test**
- Given I am a logged in user,
- When I click the logout button,
- Then I should be logged out of my account and redirected to the login page
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
