### ISSUE TITLE
[FEATURE] User Profile

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#31]
**Description**
This feature allows the user to have a user profile that they can look at. It would allow the user to edit personal information, view a list of created routes, track the user's progress (completed routes, total distance, total time e.t.c.)

**Related User Stories**
- [Update Profile Information](https://github.com/tysonkaufmann/su-go/issues/32)
- [View User Created Routes](https://github.com/tysonkaufmann/su-go/issues/38)

**Comment by tysonkaufmann** [comment]
All user stories and related dev tasks for feature have been completed. Closing issue.
