### ISSUE TITLE
[STORY] Update Profile Information

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#32]
**Story**
As a user, I should be able to edit my user profile so that I may add or update my information (name, description, photo) 

**Feature [User Profile](https://github.com/tysonkaufmann/su-go/issues/31 )**

**Related Developer Tasks**
- [Create a User Profile Information UI](https://github.com/tysonkaufmann/su-go/issues/33)
- [Create a Get User Information Endpoint](https://github.com/tysonkaufmann/su-go/issues/34)
- [Create a Change User Information Endpoint](https://github.com/tysonkaufmann/su-go/issues/35)
- [Add scripts to front-end to handle the Profile Editing](https://github.com/tysonkaufmann/su-go/issues/36)
- [Add functional for Update Profile Information](https://github.com/tysonkaufmann/su-go/issues/37)

**Acceptance Test**
- Given I am not logged in and on my profile page,
- When I click edit profile and input my updated information and click submit,
- Then my profile should be updated with my new information
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
