### ISSUE TITLE
[DEV] Create a Change User Information Endpoint

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#35]
**Related To**
- [User Profile](https://github.com/tysonkaufmann/su-go/issues/32)

**Description**
Create an API endpoint `/api/userprofile/updateuserinformation` which will serve `POST` requests:

The Body sent to the endpoint would look something like e.g **(These are subject to change)**

```
{
  "username":"",
  "fullname":"",
  "email":"",
  "profilepic":"BASE64ENCODEDIMAGE",
}
```
On Success, the API endpoint should return something like e.g **(These are subject to change)**

```
{
  "status":"200",
  "success":"true",
  "msg":"User profile updated successfully"
}
```

On Error, the API endpoint should return an error if unsuccessful e.g **(These are subject to change)**

```
{
  "status":"200",
  "success":"false",
  "msg":"An error occured while updating user profile"
}
```

**Development Steps**

- Create integration tests to fully test the API endpoint `/api/userprofile/updateuserinformation` (TDD)
- Route the endpoint in `backend/routes/userInformation`
- Create unit tests for any code added in `backend/controllers/userInformation` (TDD)
- Add code to the `backend/controllers/userInformation` to serve the API request

**Comment by chucklee9693** [comment]
Can we revisit the requirement for this ticket? @Mitul264 @tysonkaufmann @harsh071 

Do we really want to have the ability to change password in this endpoint?

- We already have endpoints for resetting password.
- In my opinion, this endpoint should only update non-auth information such as full name, picture, etc.

**Comment by Mitul264** [comment]
That's a good point! The endpoint for changing password needs a verification code passed in as well which the user might not be able to provide when they are on user profile

**Comment by chucklee9693** [comment]
> That's a good point! The endpoint for changing password needs a verification code passed in as well which the user might not be able to provide when they are on user profile

Yes, I was thinking if we still want to keep the ability to change password under User Profile, we can add a button or something in there which hits the resetpassword endpoint so that the user can go through the password resetting path we already have, and they would have the verification code this way since they would have hit that endpoint.

**Comment by chucklee9693** [comment]
So my suggestion is, we can leave the password changing functionality outside of this ticket for now, and in the near future, depending on our workload, maybe we can revisit #32 to add this functionality the way I mentioned above?

**Comment by harsh071** [comment]
> > That's a good point! The endpoint for changing password needs a verification code passed in as well which the user might not be able to provide when they are on user profile
> 
> Yes, I was thinking if we still want to keep the ability to change password under User Profile, we can add a button or something in there which hits the resetpassword endpoint so that the user can go through the password resetting path we already have, and they would have the verification code this way since they would have hit that endpoint.

This way our reset password is more secure in the front-end with the verification.

**Comment by chucklee9693** [comment]
> > > That's a good point! The endpoint for changing password needs a verification code passed in as well which the user might not be able to provide when they are on user profile
> > 
> > 
> > Yes, I was thinking if we still want to keep the ability to change password under User Profile, we can add a button or something in there which hits the resetpassword endpoint so that the user can go through the password resetting path we already have, and they would have the verification code this way since they would have hit that endpoint.
> 
> This way our reset password is more secure in the front-end with the verification.

Thanks for your input. @harsh071 

@tysonkaufmann , could you confirm this design when you are not too busy? I'll edit the ticket once you are on board.

**Comment by tysonkaufmann** [comment]
@chucklee9693 I agree with the above, we should use our existing endpoint for password changes.

**Comment by chucklee9693** [comment]
> @chucklee9693 I agree with the above, we should use our existing endpoint for password changes.

Thanks. I'll update the ticket to reflect our discussion.
