### ISSUE TITLE
[STORY] View User Created Routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#38]
**Story**
As a user, I should be able to view a list of my created routes so that I may easily see what I have created

**Feature [User Profile](https://github.com/tysonkaufmann/su-go/issues/31 )**

**Related Developer Tasks**
- [Add Scroll UI for User Created Routes](https://github.com/tysonkaufmann/su-go/issues/39)
- [Create a Routes collection and Routes model](https://github.com/tysonkaufmann/su-go/issues/40)
- [Create a Get User Created Routes Endpoint](https://github.com/tysonkaufmann/su-go/issues/41)
- [Add scripts to front-end to handle the View User Created Routes](https://github.com/tysonkaufmann/su-go/issues/42)
- [Add functional tests for View User Created Routes](https://github.com/tysonkaufmann/su-go/issues/43)

**Acceptance Test**
- Given I am a logged in user and on my profile page,
- Then I should be able to view all of the routes I have submitted to the platform
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
