### ISSUE TITLE
[DOC] Programming Standards

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#4]
**Programming Standards**
Please create a document for programming standards so that we can ensure consistency throughout the project

**Additional context**
Please add a link to the document on the ReadMe.md of the project

**Comment by tysonkaufmann** [comment]
Will need to add - branching standards, commit standards, and general coding standards if applicable. Should hopefully get the documentation done before the start of next week.

**Comment by tysonkaufmann** [comment]
Initial implementation of development standards added into the wiki: https://github.com/tysonkaufmann/su-go/wiki/Development-Standards

**Comment by tysonkaufmann** [comment]
Standards are in the wiki. Closing issue.
