### ISSUE TITLE
[STORY] View User History

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#44]
**Story**
As a user, I should be able to view my completed routes so that I may be able to track my progress

**Feature [User Profile](https://github.com/tysonkaufmann/su-go/issues/31 )**

**Related Developer Tasks**
- [Create user history scroll UI](https://github.com/tysonkaufmann/su-go/issues/45)
- [Create a Completed collection and Completed model](https://github.com/tysonkaufmann/su-go/issues/46)
- [Create a Get Completed routes endpoint](https://github.com/tysonkaufmann/su-go/issues/47)
- [Add scripts to front-end to handle the viewing of completed routes](https://github.com/tysonkaufmann/su-go/issues/48)
- [Add functional tests for viewing the completed routes](https://github.com/tysonkaufmann/su-go/issues/49)

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
