### ISSUE TITLE
[DEV] Create user history scroll UI

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#45]
**Related To**
- [View User History](https://github.com/tysonkaufmann/su-go/issues/44)

**Description**
This allows the user to be able to interact with the web application in order to scroll through routes they completed. 

**Development Steps**
- Create a scroll view and each item in the scroll should display
     1. Route Title
     2. One Route Photo
     3. Route Type
     4. Route Distance
     5. Route Time

- Link each item in the list to go to the page where the route is Viewed (Make a landing page if the route view has not yet been implemented, but don't add too much information on the route view landing page as that is for another [userstory](https://github.com/tysonkaufmann/su-go/issues/57))

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
