### ISSUE TITLE
[DEV] Create a Completed collection and Completed model

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#46]
**Related To**
- [View User History](https://github.com/tysonkaufmann/su-go/issues/44)

**Description**
Because the data will be stored in a NoSQL database we will create a collection and a model where the schema would look like,
```
NUMBER completedid
NUMBER routeid
STRING username
```

**Development Steps**
- Create a collection in MongoDB called `Completed`
- Add unit tests for functions in the model (TDD)
- Create a UserAuth model in `backend/models/completed`

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
