### ISSUE TITLE
[DEV] Create a Get Completed routes endpoint

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#47]
**Related To**
- [View User History](https://github.com/tysonkaufmann/su-go/issues/44)

**Description**
Create an API endpoint `/api/routes/usercompletedroutes/{USERNAME}` which will serve `GET` requests:

On Success, the API endpoint should return the information on success e.g **(These are subject to change)**
```
{
  "status":"200",
  "success":"true",
  "data": [
    {
      "username":"",
      "routeid":"",
      "routetitle":"",
      "routetype":"",
      "routetime":"",
      "routedistance":"",
      "routedescription":"",
      "photos":[],
      "mapdata":{}
    },
    {
      "username":"",
      "routeid":"",
      "routetitle":"",
      "routetype":"",
      "routetime":"",
      "routedistance":"",
      "routedescription":"",
      "photos":[],
      "mapdata":{}
    },
  ],
  "msg":"Routes found successfully"
}
```
On Error, the API endpoint should return an error if unsuccessful e.g **(These are subject to change)**
```
{
  "status":"200",
  "success":"false",
  "msg":"The username does not exist"
}
```

**Development Steps**

- Create integration tests to fully test the API endpoint `/api/routes/usercompletedroutes/{USERNAME}` (TDD)
- Route the endpoint in `backend/routes/routes`
- Create unit tests for any code added in `backend/controllers/routes` (TDD)
- Add code to the `backend/controllers/routes` to serve the API request

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
