### ISSUE TITLE
[DEV] Add scripts to front-end to handle the viewing of completed routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#48]
**Related To**
- [View User History](https://github.com/tysonkaufmann/su-go/issues/44)

**Description**
We will have to add scripts to the front-end to help the user browse routes they completed

**Development Steps**
- Add JavaScript code to make API requests to `/api/routes/usercompletedroutes/{USERNAME}` and success/error handle responses 
- Dont forget to include the headers `x-auth-token : TOKEN` and `x-auth-username: USERNAME`
- Add JavaScript code to handle landing to a page when a route is clicked on the list (No need to implement details on the landing page as that is part of another [userstory](https://github.com/tysonkaufmann/su-go/issues/57))

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
