### ISSUE TITLE
[DEV] Add functional tests for viewing the completed routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#49]
**Related To**
- [View User History](https://github.com/tysonkaufmann/su-go/issues/44)

**Description**
Create a functional test for the user-story above

**Development Steps**
- Use this resource to explore https://reactjs.org/docs/testing.html

**Comment by tysonkaufmann** [comment]
As of Feb 22 meeting - route completion functionality has been agreed to not be within this projects scope (user tracking is not a priority). Marking all related issues as out of scope and closing.
