### ISSUE TITLE
[FEATURE] User Login

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#5]
**Description**
This feature allows the user to log in, Signup and Reset Password. 

**Related User Stories**
- [User Login](https://github.com/tysonkaufmann/su-go/issues/6 )
- [User Signup](https://github.com/tysonkaufmann/su-go/issues/13)
- [Reset Password](https://github.com/tysonkaufmann/su-go/issues/19)
- [Logout](https://github.com/tysonkaufmann/su-go/issues/27)

**Comment by tysonkaufmann** [comment]
All user stories and related dev tasks for feature have been completed. Closing issue.
