### ISSUE TITLE
[FEATURE] Route Management

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#50]
**Description**
This feature helps the user to add a route, view a route, view a point of interest, delete a route, start a route. 

**Related User Stories**
- [Add a route](https://github.com/tysonkaufmann/su-go/issues/51)
- [View a route](https://github.com/tysonkaufmann/su-go/issues/57)
- [Delete a route](https://github.com/tysonkaufmann/su-go/issues/62)
- [Start and End a route](https://github.com/tysonkaufmann/su-go/issues/66)
- [View Traffic](https://github.com/tysonkaufmann/su-go/issues/75)

**Comment by tysonkaufmann** [comment]
All user stories have been completed with passing acceptance tests. Feature is completed. Closing issue.
