### ISSUE TITLE
[STORY] Add a route

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#51]
**Story**
As a user, I should be able to add a route to the platform so that others may participate in it

**Feature [Route Management](https://github.com/tysonkaufmann/su-go/issues/50 )**

**Related Developer Tasks**
- [Create a Add Route UI](https://github.com/tysonkaufmann/su-go/issues/52)
- [Create an Add Route Endpoint](https://github.com/tysonkaufmann/su-go/issues/53)
- [Add scripts to front-end to handle the Add Route](https://github.com/tysonkaufmann/su-go/issues/55)
- [Add functional tests for Add Route](https://github.com/tysonkaufmann/su-go/issues/56)

**Acceptance Test**
- Given I am a logged in user and I am on the home page,
- When I click the add route button and fill in my route information and click submit,
- Then my route should be added to the route database
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
