### ISSUE TITLE
[STORY] View a route

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#57]
**Story**
As a user, I should be able to view a route on the platform so that I may participate in it

**Feature [Route Management](https://github.com/tysonkaufmann/su-go/issues/50 )**

**Related Developer Tasks**
- [Add UI for View a Route](https://github.com/tysonkaufmann/su-go/issues/58)
- [Add an endpoint to Get Route Information](https://github.com/tysonkaufmann/su-go/issues/59)
- [Add scripts to front-end to handle the view route](https://github.com/tysonkaufmann/su-go/issues/60)
- [Add functional tests for View Route](https://github.com/tysonkaufmann/su-go/issues/61)

**Acceptance Test**
- Given I am a logged in user,
- When I click the user profile button and browse to my created routes,
- Then I will be able to view the route details on each of my created routes
- [x] Passes

**Additional Notes**
- This story and related acceptance test covers viewing routes a user has created by the user that created them. Viewing other routes created by other users is covered within the feature #79

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
