### ISSUE TITLE
[STORY] Login

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#6]
**Story**
As a user, I should be able to log in using my username and password so that I may access my account

**Feature [User Login](https://github.com/tysonkaufmann/su-go/issues/5 )**

**Related Developer Tasks**
- [Create Login UI](https://github.com/tysonkaufmann/su-go/issues/7)
- [Create an Auth collection and UserAuth model](https://github.com/tysonkaufmann/su-go/issues/9)
- [Create a user login endpoint](https://github.com/tysonkaufmann/su-go/issues/8)
- [Add JS Code to persist the user's session](https://github.com/tysonkaufmann/su-go/issues/89)
- [Add scripts to front-end to handle the login](https://github.com/tysonkaufmann/su-go/issues/11)
- [Add functional tests for login](https://github.com/tysonkaufmann/su-go/issues/12)

**Acceptance Test**
- Given I am not logged in and on the login page,
- When I enter my correct username and password then click the login button,
- Then I should be logged in and redirected to the landing page
- [x] Passes

**Comment by tysonkaufmann** [comment]
All dev tasks for user story have been completed. Closing issue.
