### ISSUE TITLE
[STORY] Delete a route

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#62]
**Story**
As a user, I should be able to delete a route that I created previously so other users can no longer see it

**Feature [Route Management](https://github.com/tysonkaufmann/su-go/issues/50 )**

**Related Developer Tasks**
- [Create a Delete Route endpoint](https://github.com/tysonkaufmann/su-go/issues/64)
- [Make changes to the UI and add front-end code](https://github.com/tysonkaufmann/su-go/issues/63)
- [Create Functional Tests for Deleting routes](https://github.com/tysonkaufmann/su-go/issues/65)

**Acceptance Test**
- Given I am a logged in user and I am browsing a route I have created,
- When I click the delete button and click yes on the pop-up confirmation,
- Then the route that I had created should be deleted from the application
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
