### ISSUE TITLE
[DEV] Create Functional Tests for Deleting routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#65]
**Related To**
- [Delete Route](https://github.com/tysonkaufmann/su-go/issues/62)

**Description**
Create a functional test for the user-story above

**Development Steps**
- Use this resource to explore https://reactjs.org/docs/testing.html

**Comment by tysonkaufmann** [comment]
Tests added within individual related issues. Ticket is invalid - closing
