### ISSUE TITLE
[STORY] Start and End a route

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#66]
**Story**
As a user, I should be able to start and end a route so others may be informed on how active a route is

**Feature [Route Management](https://github.com/tysonkaufmann/su-go/issues/50 )**

**Related Developer Tasks**
- [Create a Traffic collection and Traffic model](https://github.com/tysonkaufmann/su-go/issues/67)
- [Create a Start Route endpoint](https://github.com/tysonkaufmann/su-go/issues/68)
- [Create a Current User Route endpoint](https://github.com/tysonkaufmann/su-go/issues/69)
- [Create an End Route endpoint](https://github.com/tysonkaufmann/su-go/issues/70)
- [Make changes to the UI and add front-end code](https://github.com/tysonkaufmann/su-go/issues/71)
- [Create Functional Tests for Start and End routes](https://github.com/tysonkaufmann/su-go/issues/72)

**Acceptance Test 1**
- Given I am a logged in user and I am browsing a route,
- When I click the start route button,
- Then that route should become my active route that will expire in 6 hours
- [x] Passes

**Acceptance Test 2**
- Given I am a logged in user and I am browsing my active route,
- When I click the end route button,
- Then I should no longer have an active route
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance tests pass. Closing issue.
