### ISSUE TITLE
[DEV] Create Functional Tests for Start and End routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#72]
**Related To**
- [Start and End a route](https://github.com/tysonkaufmann/su-go/issues/66 )

**Description**
Create a functional test for the user-story above

**Development Steps**
- Use this resource to explore https://reactjs.org/docs/testing.html

**Comment by tysonkaufmann** [comment]
Tests added within individual related issues. Ticket is invalid - closing
