### ISSUE TITLE
[STORY] View Traffic

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#75]
**Story**
As a user, I should be able to view current traffic so that I may see how active a route is

**Feature [Route Management](https://github.com/tysonkaufmann/su-go/issues/50 )**

**Related Developer Tasks**
- [Create a view traffic endpoint](https://github.com/tysonkaufmann/su-go/issues/76)
- [Make changes to the UI and add front-end code](https://github.com/tysonkaufmann/su-go/issues/77)
- [Create Functional Tests for view user traffic](https://github.com/tysonkaufmann/su-go/issues/78)

**Acceptance Test**
- Given I am a logged in user and I am browsing a route,
- When I browse to the route details,
- Then I should see the amount of people currently on that route
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
