### ISSUE TITLE
[FEATURE] Search / Overview Map

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#79]
**Description**
This feature allows the user to view a list of routes on the homepage, filter routes by type/province/city, and sort routes by distance/time

**Related User Stories**
- [View and Filter Routes on the Homepage](https://github.com/tysonkaufmann/su-go/issues/80)
- [Sort Routes](https://github.com/tysonkaufmann/su-go/issues/84)

**Comment by tysonkaufmann** [comment]
All user stories have been completed with passing acceptance tests. Feature is completed. Closing issue.
