### ISSUE TITLE
[STORY] View and Filter Routes on the Homepage

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#80]
**Story**
As a user, I should be able view and filter routes by their identifiable criteria so that I may easily find a route I want to take

**[Feature Search/Overview Map](https://github.com/tysonkaufmann/su-go/issues/79 )**

**Related Developer Tasks**
- [Create an endpoint to get a list of routes](https://github.com/tysonkaufmann/su-go/issues/81)
- [Create Scroll UI on the homepage and add JS code to make it interactive](https://github.com/tysonkaufmann/su-go/issues/82)
- [Create Functional tests to test viewing and filtering routes on the homepage ](https://github.com/tysonkaufmann/su-go/issues/83)

**Acceptance Test**
- Given I am a logged in user and I am browsing all routes,
- When I select a route type from the filter dropdown box,
- Then I should only see routes with that given type on the route page
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
