### ISSUE TITLE
[DEV] Create an endpoint to get a list of routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#81]
**Related To**
- [View and Filter Routes on the Homepage](https://github.com/tysonkaufmann/su-go/issues/80)

**Description**
Create an API endpoint `/api/routes` which will serve `GET` requests and sends : 

On Success, the API endpoint should return the information on success e.g **(These are subject to change)**
```
{
  "status":"200",
  "success":"true",
  "data": [
    {
      "username":"",
      "routeid":"",
      "routetitle":"",
      "routetype":"",
      "routetime":"",
      "routedistance":"",
      "routedescription":"",
      "photos":[],
      "mapdata":{}
    },
    {
      "username":"",
      "routeid":"",
      "routetitle":"",
      "routetype":"",
      "routetime":"",
      "routedistance":"",
      "routedescription":"",
      "photos":[],
      "mapdata":{}
    },
  ]
}
```
We will not return an error, instead, we will return an empty list of routes e.g
```
{
  "status":"200",
  "success":"true",
  "data": []
}
```

**Development Steps**

- Create integration tests to fully test the API endpoint  `/api/routes` (TDD)
- Route the endpoint in `backend/routes/routes`
- Create unit tests for any code added in `backend/controllers/routes` (TDD)
- Add code to the `backend/controllers/routes` to serve the API request

**Comment by tysonkaufmann** [comment]
Functionality will instead be added to the front end. Closing issue
