### ISSUE TITLE
[DEV] Create Functional tests to test viewing and filtering routes on the homepage

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#83]
**Related To**
- [View and Filter Routes on the Homepage](https://github.com/tysonkaufmann/su-go/issues/80)

**Description**
Create a functional test for the user-story above

**Development Steps**
- Use this resource to explore https://reactjs.org/docs/testing.html

**Comment by tysonkaufmann** [comment]
Tests added within individual related issues. Ticket is invalid - closing
