### ISSUE TITLE
[STORY] Sort Routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#84]
**Story**
As a user, I should be able to sort routes by distance, time, and traffic so that I may be able to get more preferred routes

**We want to push this complexity to the client-side**

**[Feature Search/Overview Map](https://github.com/tysonkaufmann/su-go/issues/79 )**

**Related Developer Tasks**
- [Update the UI for Sort and Sort using JS](https://github.com/tysonkaufmann/su-go/issues/85)
- [Create Functional Tests for Sorting Routes](https://github.com/tysonkaufmann/su-go/issues/86)

**Acceptance Test**
- Given I am a logged in user and I am browsing all routes,
- When I click on the sort dropdown and select a sort type,
- Then the routes in the sidebar will be sorted based on that type
- [x] Passes

**Comment by tysonkaufmann** [comment]
All developer tasks completed. Acceptance test passes. Closing issue.
