### ISSUE TITLE
[DEV] Create Functional Tests for Sorting Routes

### ISSUE THREAD

**Issue by Mitul264** [tysonkaufmann/su-go#86]
**Related To**
- [Sort Routes](https://github.com/tysonkaufmann/su-go/issues/84)

**Description**
Create a functional test for the user-story above

**Development Steps**
- Use this resource to explore https://reactjs.org/docs/testing.html

**Comment by tysonkaufmann** [comment]
Tests added within individual related issues. Ticket is invalid - closing
